# Importing Libraries

In [1]:
import pandas as pd
import numpy as np

# Importing DataFrame 

In [21]:
df=pd.read_csv('exp.csv')

In [22]:
df.head()

actual    exp  variation  Layer Height (µm  Exposure Time (sec.)  \
0    12.0  11.94      -0.06              0.05                   2.0   
1    12.0  12.15       0.15              0.05                   2.0   
2    12.0  11.92      -0.08              0.05                   2.0   
3    12.0  11.94      -0.06              0.05                   2.5   
4    12.0  12.00       0.00              0.05                   2.5   

   Light off Display (sec.) Orientation  Series series  
0                      13.0           X     1.0     1X  
1                      13.0           Y     1.0     1Y  
2                      13.0           Z     1.0     1Z  
3                      13.0           X     2.0     2X  
4                      13.0           Y     2.0     2Y

# Data Filteration

In [23]:
df.columns

Index(['actual', 'exp', 'variation', 'Layer Height (µm',
       'Exposure Time (sec.)', 'Light off Display (sec.)', 'Orientation',
       'Series', 'series'],
      dtype='object')

In [24]:
df=df.drop(['actual', 'exp','Series', 'series'],axis='columns')

In [25]:
df.head()

variation  Layer Height (µm  Exposure Time (sec.)  \
0      -0.06              0.05                   2.0   
1       0.15              0.05                   2.0   
2      -0.08              0.05                   2.0   
3      -0.06              0.05                   2.5   
4       0.00              0.05                   2.5   

   Light off Display (sec.) Orientation  
0                      13.0           X  
1                      13.0           Y  
2                      13.0           Z  
3                      13.0           X  
4                      13.0           Y

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   variation                 45 non-null     float64
 1   Layer Height (µm          45 non-null     float64
 2   Exposure Time (sec.)      45 non-null     float64
 3   Light off Display (sec.)  45 non-null     float64
 4   Orientation               45 non-null     object 
dtypes: float64(4), object(1)
memory usage: 2.0+ KB


# Applying Label Encoding For Orientation Column 

In [27]:
from sklearn.preprocessing import LabelEncoder
df.Orientation=LabelEncoder().fit_transform(df.Orientation)

In [28]:
df.head()

variation  Layer Height (µm  Exposure Time (sec.)  \
0      -0.06              0.05                   2.0   
1       0.15              0.05                   2.0   
2      -0.08              0.05                   2.0   
3      -0.06              0.05                   2.5   
4       0.00              0.05                   2.5   

   Light off Display (sec.)  Orientation  
0                      13.0            0  
1                      13.0            1  
2                      13.0            2  
3                      13.0            0  
4                      13.0            1

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   variation                 45 non-null     float64
 1   Layer Height (µm          45 non-null     float64
 2   Exposure Time (sec.)      45 non-null     float64
 3   Light off Display (sec.)  45 non-null     float64
 4   Orientation               49 non-null     int32  
dtypes: float64(4), int32(1)
memory usage: 1.8 KB


In [30]:
df.dropna(inplace=True)

In [31]:
df.rename(columns={'Layer Height (µm':'lr_h','Exposure Time (sec.)':'exp_t','Light off Display (sec.)':'lod'},inplace=True)

In [33]:
df.columns

Index(['variation', 'lr_h', 'exp_t', 'lod', 'Orientation'], dtype='object')

In [34]:
df.head()

variation  lr_h  exp_t   lod  Orientation
0      -0.06  0.05    2.0  13.0            0
1       0.15  0.05    2.0  13.0            1
2      -0.08  0.05    2.0  13.0            2
3      -0.06  0.05    2.5  13.0            0
4       0.00  0.05    2.5  13.0            1

In [35]:
x=df.drop(['exp_t','lod','lr_h'],axis='columns')
y=df.drop(['variation','Orientation'],axis='columns')

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

# By Linear Regression

In [36]:
from sklearn.linear_model import LinearRegression
lr_model=LinearRegression()
lr_model.fit(x_train,y_train)

LinearRegression()

In [38]:
lr_model.predict([[0,1]])

array([[ 0.07521175,  2.25893513, 13.03120932]])

In [39]:
lr_model.predict([[0,0]])

array([[ 0.07438597,  2.23291554, 13.177971  ]])

# By Decision Tree Regression

In [40]:
from sklearn.tree import DecisionTreeRegressor
dtr_model=DecisionTreeRegressor()
dtr_model.fit(x_train,y_train)

DecisionTreeRegressor()

In [41]:
dtr_model.predict([[0,1]])

array([[ 0.05,  2.5 , 13.  ]])

In [42]:
dtr_model.predict([[0,0]])

array([[ 0.05,  2.25, 14.  ]])

# By Random Forest Regression

In [43]:
from sklearn.ensemble import RandomForestRegressor
rfr_model=RandomForestRegressor()
rfr_model.fit(x_train,y_train)

RandomForestRegressor()

In [45]:
rfr_model.predict([[0,1]])

array([[ 0.0615    ,  2.42958333, 13.01833333]])

In [46]:
rfr_model.predict([[0,0]])

array([[ 0.0625  ,  2.254375, 13.6375  ]])

# By LinearSVR

In [48]:
from sklearn.svm import LinearSVR
svr_model=LinearSVR()
svr_model.fit(x_train,y_train)

ValueError: y should be a 1d array, got an array of shape (36, 3) instead.

# By MultiOutput Regression

In [49]:
from sklearn.multioutput import MultiOutputRegressor
multi_model=MultiOutputRegressor(svr_model)
multi_model.fit(x_train,y_train)

MultiOutputRegressor(estimator=LinearSVR())

In [50]:
multi_model.predict([[0,0]])

array([[ 0.07498945,  2.24990934, 12.00079528]])

In [51]:
multi_model.predict([[0,1]])

array([[ 0.07499671,  2.25004142, 12.50012016]])

In [52]:
from sklearn.multioutput import MultiOutputRegressor
multi_model=MultiOutputRegressor(lr_model)
multi_model.fit(x_train,y_train)

MultiOutputRegressor(estimator=LinearRegression())

In [53]:
multi_model.predict([[0,1]])

array([[ 0.07521175,  2.25893513, 13.03120932]])

In [54]:
multi_model.predict([[0,0]])

array([[ 0.07438597,  2.23291554, 13.177971  ]])

In [55]:
df[df['variation']==0.00]

variation  lr_h  exp_t   lod  Orientation
4        0.0  0.05   2.50  13.0            1
9        0.0  0.05   2.25  14.0            0

# Cross Validation Score

In [58]:
from sklearn.model_selection import cross_val_score
cross_val_score(lr_model,x_test,y_test,scoring='neg_mean_squared_error',cv=5)

array([-0.73590087, -1.0608868 , -0.08537348, -0.09230917, -0.19406572])

# Calculating Mean Square Error

### For linear regression model with respect to multi model prediction

In [60]:
from sklearn.metrics import mean_squared_error
y_pred=multi_model.predict(x_test)

mean_sq_error=np.sqrt(mean_squared_error(y_test,y_pred))

In [61]:
mean_sq_error

0.5632190859893824

### For Decision tree regression

In [62]:
y_pred=dtr_model.predict(x_test)

mean_sq_error=np.sqrt(mean_squared_error(y_test,y_pred))

In [63]:
mean_sq_error

0.8155320917000095

### For Random Forest Regression

In [64]:
y_pred=rfr_model.predict(x_test)

mean_sq_error=np.sqrt(mean_squared_error(y_test,y_pred))

In [65]:
mean_sq_error

0.77175630242495