# Importing Libraries

In [48]:
import pandas as pd
import numpy as np

# Importing DataFrame 

- Here **lr_h** is refering to **Layer Height**
- **exp_t** is **Exposure Time**
- **lod** is **Light of Display**

In [59]:
df=pd.read_csv('exp - Copy.csv')

In [60]:
df.head()

actual    exp  variation  lr_h  exp_t  lod orient  Series series
0     4.3  4.165      0.135  0.05    2.0   13      X       1     1X
1     4.3  4.122      0.178  0.05    2.0   13      Y       1     1Y
2     4.3  4.148      0.152  0.05    2.0   13      Z       1     1Z
3     4.3  4.140      0.160  0.05    2.5   13      X       2     2X
4     4.3  4.102      0.198  0.05    2.5   13      Y       2     2Y

# Data Filteration

In [61]:
df.columns

Index(['actual', 'exp', 'variation', 'lr_h', 'exp_t', 'lod', 'orient',
       'Series', 'series'],
      dtype='object')

In [62]:
df=df.drop(['actual', 'exp','Series', 'series'],axis='columns')

In [63]:
df.head()

variation  lr_h  exp_t  lod orient
0      0.135  0.05    2.0   13      X
1      0.178  0.05    2.0   13      Y
2      0.152  0.05    2.0   13      Z
3      0.160  0.05    2.5   13      X
4      0.198  0.05    2.5   13      Y

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   variation  45 non-null     float64
 1   lr_h       45 non-null     float64
 2   exp_t      45 non-null     float64
 3   lod        45 non-null     int64  
 4   orient     45 non-null     object 
dtypes: float64(3), int64(1), object(1)
memory usage: 1.9+ KB


# Applying One Hot Encoding For Orientation Column 

In [71]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
x=pd.DataFrame(encoder.fit_transform(df[['orient']]).toarray())

In [73]:
df=pd.concat([df,x],axis='columns')

In [74]:
df.head()

variation  lr_h  exp_t  lod orient    0    1    2
0      0.135  0.05    2.0   13      X  1.0  0.0  0.0
1      0.178  0.05    2.0   13      Y  0.0  1.0  0.0
2      0.152  0.05    2.0   13      Z  0.0  0.0  1.0
3      0.160  0.05    2.5   13      X  1.0  0.0  0.0
4      0.198  0.05    2.5   13      Y  0.0  1.0  0.0

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   variation  45 non-null     float64
 1   lr_h       45 non-null     float64
 2   exp_t      45 non-null     float64
 3   lod        45 non-null     int64  
 4   orient     45 non-null     object 
 5   0          45 non-null     float64
 6   1          45 non-null     float64
 7   2          45 non-null     float64
dtypes: float64(6), int64(1), object(1)
memory usage: 2.9+ KB


In [76]:
df.drop(['orient'],axis='columns', inplace=True)

In [79]:
df.rename(columns={0:'x', 1: 'y',2 :'z'},inplace=True)

In [80]:
df.columns

Index(['variation', 'lr_h', 'exp_t', 'lod', 'x', 'y', 'z'], dtype='object')

In [81]:
df.head()

variation  lr_h  exp_t  lod    x    y    z
0      0.135  0.05    2.0   13  1.0  0.0  0.0
1      0.178  0.05    2.0   13  0.0  1.0  0.0
2      0.152  0.05    2.0   13  0.0  0.0  1.0
3      0.160  0.05    2.5   13  1.0  0.0  0.0
4      0.198  0.05    2.5   13  0.0  1.0  0.0

In [88]:
x=df[['variation','x','y','z']]
y=df.drop(['variation','x','y','z'],axis='columns')

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

# By Linear Regression

In [89]:
from sklearn.linear_model import LinearRegression
lr_model=LinearRegression()
lr_model.fit(x_train,y_train)

LinearRegression()

In [91]:
lr_model.predict([[0,1,0,0]])

array([[ 0.06564871,  2.27207542, 13.6396086 ]])

In [93]:
lr_model.predict([[0,0,0,1]])

array([[ 0.0684655 ,  2.27513452, 13.71758272]])

# By Decision Tree Regression

In [94]:
from sklearn.tree import DecisionTreeRegressor
dtr_model=DecisionTreeRegressor()
dtr_model.fit(x_train,y_train)

DecisionTreeRegressor()

In [95]:
dtr_model.predict([[0,1,0,0]])

array([[ 0.075,  2.25 , 13.   ]])

In [96]:
dtr_model.predict([[0,0,0,1]])

array([[ 0.075,  2.25 , 13.   ]])

# By Random Forest Regression

In [97]:
from sklearn.ensemble import RandomForestRegressor
rfr_model=RandomForestRegressor()
rfr_model.fit(x_train,y_train)

RandomForestRegressor()

In [98]:
rfr_model.predict([[0,1,0,0]])

array([[ 0.07425,  2.31   , 13.13   ]])

In [99]:
rfr_model.predict([[0,0,0,1]])

array([[ 0.0753,  2.3185, 12.962 ]])

# By LinearSVR

In [100]:
from sklearn.svm import LinearSVR
svr_model=LinearSVR()
svr_model.fit(x_train,y_train)

ValueError: y should be a 1d array, got an array of shape (36, 3) instead.

# By MultiOutput Regression

In [101]:
from sklearn.multioutput import MultiOutputRegressor
multi_model=MultiOutputRegressor(svr_model)
multi_model.fit(x_train,y_train)

MultiOutputRegressor(estimator=LinearSVR())

In [103]:
multi_model.predict([[0,0,0,1]])

array([[ 0.07498297,  2.24983316, 12.85344219]])

In [104]:
multi_model.predict([[0,1,0,0]])

array([[ 0.07498166,  2.24977672, 12.8543667 ]])

In [105]:
from sklearn.multioutput import MultiOutputRegressor
multi_model=MultiOutputRegressor(lr_model)
multi_model.fit(x_train,y_train)

MultiOutputRegressor(estimator=LinearRegression())

In [106]:
multi_model.predict([[0,1,0,0]])

array([[ 0.06564871,  2.27207542, 13.6396086 ]])

In [107]:
multi_model.predict([[0,0,0,1]])

array([[ 0.0684655 ,  2.27513452, 13.71758272]])

In [108]:
df[df['variation']==0.00]

Empty DataFrame
Columns: [variation, lr_h, exp_t, lod, x, y, z]
Index: []

# Cross Validation Score

In [133]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
cv=ShuffleSplit(n_splits=5,test_size=0.2,random_state=0)
cross_val_score(LinearRegression(),x_test,y_test,cv=cv,scoring='neg_mean_squared_error')

array([-0.9093371 , -0.53309107, -0.37732479, -0.46624296, -0.20661524])

# Calculating Mean Square Error

### For linear regression model with respect to multi model prediction

In [114]:
from sklearn.metrics import mean_squared_error
y_pred=multi_model.predict(x_test)

mean_sq_error=np.sqrt(mean_squared_error(y_test,y_pred))

In [115]:
mean_sq_error

0.5648400902372034

### For Decision tree regression

In [116]:
y_pred=dtr_model.predict(x_test)

mean_sq_error=np.sqrt(mean_squared_error(y_test,y_pred))

In [117]:
mean_sq_error

0.5570673873725459

### For Random Forest Regression

In [118]:
y_pred=rfr_model.predict(x_test)

mean_sq_error=np.sqrt(mean_squared_error(y_test,y_pred))

In [119]:
mean_sq_error

0.5260675267351002

# GridSearchCV For Estimating Best Model With Diff. Params

In [125]:
from sklearn.model_selection import GridSearchCV
def find_best_model(x,y):
    algos={
        'linear_regression':{
            'model':LinearRegression(),
            'params':{
                'normalize':[True, False],
                'fit_intercept':[True,False],
                'n_jobs':[1,2,3]
            }
        },
        'Decision_tree_regression':{
            'model':DecisionTreeRegressor(),
            'params':{
                'criterion':['mse',"friedman_mse"],
                'splitter' : ["best", "random"],
                
            }
        },
        'RandomForest':{
            'model':RandomForestRegressor(),
            'params':{
                'criterion':['mse',"friedman_mse"]
                
            }
        }
    }
    
    score=[]
    for algo_name, config in algos.items():
        gs=GridSearchCV(config['model'],config['params'],cv=5)
        gs.fit(x,y)
        score.append({
            'model':algo_name,
            'best_score':gs.best_score_,
            'best_params':gs.best_params_
        })
    return pd.DataFrame(score,columns=['model','best_score','best_params'])

In [134]:
find_best_model(x,y)

model  best_score  \
0         linear_regression   -0.815654   
1  Decision_tree_regression   -2.108333   
2              RandomForest   -1.247150   

                                         best_params  
0  {'fit_intercept': True, 'n_jobs': 1, 'normaliz...  
1  {'criterion': 'friedman_mse', 'splitter': 'best'}  
2                      {'criterion': 'friedman_mse'}

In [128]:
from sklearn.linear_model import LinearRegression
lr_model=LinearRegression(fit_intercept= True, n_jobs= 1, normalize= False)
lr_model.fit(x_train,y_train)

LinearRegression(n_jobs=1)

In [129]:
lr_model.predict([[0,0,0,1]])

array([[ 0.0684655 ,  2.27513452, 13.71758272]])

In [130]:
y_pred=lr_model.predict(x_test)

mean_sq_error=np.sqrt(mean_squared_error(y_test,y_pred))

In [131]:
mean_sq_error

0.5648400902372034